a = int(input("a="))
b = int(input("b="))
print("a+b=", a+b)
print("a-b=", a-b)
print("a*b=", a*b)
print("a/b=", a/b)

name = input("What is your name?")
age = input("How old are you?")
place = input("Where do you live?")
print("Hello", name, "Your age is", age, "You live in", place)
